apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qh8n1s6ig-java-springboot
  janus-idp.io/tekton: qh8n1s6ig-java-springboot
  backstage.io/kubernetes-id: qh8n1s6ig-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qh8n1s6ig-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
